/**
 * Modules Index
 * Re-exports all API modules
 */

export { authApi } from "./auth.api"
export { studentApi } from "./student.api"
export { studentProfileApi } from "./studentProfile.api"
export { hostelApi } from "./hostel.api"
export { adminApi } from "./admin.api"
export { wardenApi, associateWardenApi, hostelSupervisorApi } from "./warden.api"
export { visitorApi } from "./visitor.api"
export { leaveApi } from "./leave.api"
export { complaintApi } from "./complaint.api"
export { securityApi } from "./security.api"
export { maintenanceApi } from "./maintenance.api"
export { eventsApi } from "./events.api"
export { lostAndFoundApi } from "./lostAndFound.api"
export { inventoryApi } from "./inventory.api"
export { healthApi } from "./health.api"
export { feedbackApi } from "./feedback.api"
export { taskApi } from "./task.api"
export { statsApi } from "./stats.api"
export { dashboardApi } from "./dashboard.api"
export { uploadApi } from "./upload.api"
export { notificationApi } from "./notification.api"
export { alertApi } from "./alert.api"
export { userApi } from "./user.api"
export { accessControlApi } from "./accessControl.api"
export { certificateApi } from "./certificate.api"
export { idCardApi } from "./idCard.api"
export { hostelGateApi } from "./hostelGate.api"
export { insuranceProviderApi } from "./insuranceProvider.api"
export { liveCheckInOutApi } from "./liveCheckInOut.api"
export { onlineUsersApi } from "./onlineUsers.api"
export { sheetApi } from "./sheet.api"
export { superAdminApi } from "./superAdmin.api"
export { undertakingApi } from "./undertaking.api"
export { discoApi } from "./disco.api"
export { faceScannerApi } from "./faceScanner.api"
export { jrAppointmentsApi } from "./jrAppointments.api"
