// Admin Pages - Barrel Export
export { default as AdminManagementPage } from './AdminManagementPage'
export { default as AssociateWardensPage } from './AssociateWardensPage'
export { default as DashboardPage } from './DashboardPage'
export { default as FaceScannersPage } from './FaceScannersPage'
export { default as HostelsPage } from './HostelsPage'
export { default as HostelSupervisorsPage } from './HostelSupervisorsPage'
export { default as InventoryPage } from './InventoryPage'
export { default as LiveCheckInOutPage } from './LiveCheckInOutPage'
export { default as MaintenanceStaffPage } from './MaintenanceStaffPage'
export { default as OthersPage } from './OthersPage'
export { default as SecurityLoginsPage } from './SecurityLoginsPage'
export { default as SettingsPage } from './SettingsPage'
export { default as SheetPage } from './SheetPage'
export { default as TaskManagementPage } from './TaskManagementPage'
export { default as UpdatePasswordPage } from './UpdatePasswordPage'
export { default as WardensPage } from './WardensPage'
